### ISSUE TITLE
Document how to work when inside `with-temp-buffer`

### ISSUE THREAD

**Issue by alhassy** [DarwinAwardWinner/with-simulated-input#11]
I expected the following test to show a string containing the word `hello` enclosed in a `src` block tagged `emacs-lisp`, but instead it errors out.

     (with-temp-buffer
       (insert "hello")
       (goto-char (point-min))
       (set-mark-command nil)
       (goto-char (point-max))
       (with-simulated-input
           "emacs-lisp"
         (org-babel-demarcate-block))
       (buffer-string))

In case the error is something to do with `org-babel-demarcate-block`, I've also tried with a home-backed function `what-do` and we obtain the same error.

     (defun what-do ()
       "Alter a region of text; if no selected text, do nothing.
     Action to be done is selected from a menu."
       (interactive)
       (when (use-region-p)
         (let ((it (intern (completing-read "What do? " '(upcase downcase capitalize))))
               (txt (buffer-substring-no-properties (region-beginning) (region-end))))
           (delete-region (region-beginning) (region-end))
           (insert (funcall it txt)))))
     
     (with-temp-buffer
       (insert "hello")
       (mark-whole-buffer)
       (with-simulated-input
           "upcase"
         (what-do))
       (buffer-string))
     
This is related to issue #4.     

The [tests](https://github.com/DarwinAwardWinner/with-simulated-input/blob/master/tests/test-with-simulated-input.el)  show that the following should pass:

    (it "should work inside code that switches buffer (issue #4)"
      (let ((orig-current-buffer (current-buffer)))
        (with-temp-buffer
          (let ((temp-buffer (current-buffer)))
            (with-simulated-input "a" (read-char))
            (expect (current-buffer) :to-equal temp-buffer)
            (expect (current-buffer) :not :to-equal orig-current-buffer)))))

But I could not get this to work for my uses cases above.

Since this issue of buffers has arisen multiple times, #4 and #11, it would seem prudent to document
how to use `with-simulated-input` with different buffers in the README.

**Comment by DarwinAwardWinner** [comment]
I don't think this has anything to do with buffer switching. When I run these pieces of code, I get the error "Reached end of simulated input while evaluating body", which is the expected result because your input doesn't include RET at the end, so the function never returns. The following works fine and returns `"HELLO"`:

```elisp
(with-temp-buffer
  (insert "hello")
  (mark-whole-buffer)
  (with-simulated-input
      "upcase RET"
    (what-do))
  (buffer-string))
```

**Comment by alhassy** [comment]
Thanks for pointing that out; however, adding the missing `RET` to the first use case results in the same error...

```
 (with-temp-buffer
   (insert "hello")
   (mark-whole-buffer)
   (with-simulated-input
       "emacs-lisp RET"
     (org-babel-demarcate-block))
   (buffer-string))
```

**Comment by DarwinAwardWinner** [comment]
It looks like you posted an empty code block. For me, adding RET to the input sequence of either of the code examples above fixes them.

**Comment by DarwinAwardWinner** [comment]
There hasn't been a reply on this for over a year, so I'm closing it. If it's still a problem, feel free to provide additional information and reopen it.
