### ISSUE TITLE
Tracking use of with-simulated-input runtime eval of KEYS

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/with-simulated-input#13]
I am considering changing the semantics of the KEYS argument to `with-simulated-input` in a backward-incompatible way, and I would like to estimate how many downstream users of the package would be affected by this change. I will attempt to list every use of runtime-evaluated KEYS on Github here.

**Comment by DarwinAwardWinner** [comment]
Here are all the packages using with-simulated-input that I can find on Github:

- Spiral: https://github.com/Unrepl/spiral/blob/master/tests/test-repl.el
- org-generate: https://github.com/conao3/org-generate.el/blob/master/org-generate-tests.el
- org-ql: https://github.com/alphapapa/org-ql/blob/master/tests/test-org-ql.el
- auctex-cluttex: https://github.com/tsuu32/auctex-cluttex/blob/master/tests/test-auctex-cluttex.el
- hyperbole: https://github.com/emacs-straight/hyperbole/blob/master/test/hy-test-dependencies.el
- xwwp: https://github.com/canatella/xwwp/blob/master/test/xwwp-follow-link-test.el
- org-glance: https://github.com/rails-to-cosmos/org-glance/blob/master/test/org-glance-views-test.el
- tiqsi-emacs: https://github.com/SerialDev/tiqsi-emacs/blob/master/modules/programming/programming-clojure.el
- shell-plus: https://github.com/0x0049/shell-plus/blob/master/test/shell+-test.el
- i-ching: https://github.com/zzkt/i-ching/blob/endless/tests.el
- org-gtd: https://github.com/Trevoke/org-gtd.el/blob/master/test/org-gtd-test.el
- virtualenvwrapper.el: https://github.com/porterjamesj/virtualenvwrapper.el/blob/master/test/virtualenvwrapper-test.el
- rbtagger: https://github.com/thiagoa/rbtagger/blob/master/test/rbtagger-test.el
- ebib: https://github.com/joostkremers/ebib/blob/master/test/ebib-test.el
- frog-menu: https://github.com/clemera/frog-menu/blob/master/test/frog-menu-test.el

(Note: I used Github's code search to find these, so there is no guarantee that I'm pointing at the canonical repo for each.)

**Comment by DarwinAwardWinner** [comment]
Found instances of runtime eval:

- spiral
  - https://github.com/Unrepl/spiral/blob/master/tests/test-spiral-connect.el#L54
- org-ql
  - https://github.com/alphapapa/org-ql/blob/master/tests/test-org-ql.el#L1447
  - https://github.com/alphapapa/org-ql/blob/master/tests/test-org-ql.el#L1488
  - https://github.com/alphapapa/org-ql/blob/master/tests/test-org-ql.el#L1501
- xwwp
  - https://github.com/canatella/xwwp/blob/master/test/xwwp-follow-link-test.el#L188
- virtualenvwrapper.el
  - https://github.com/porterjamesj/virtualenvwrapper.el/blob/master/test/virtualenvwrapper-test.el#L83

**Comment by nbfalcon** [comment]
`xwwp` is a false positive, since it uses `'(...)`, which will work just fine.

**Comment by DarwinAwardWinner** [comment]
This is no longer needed, as #12 has been merged.
