### ISSUE TITLE
strange when it's in a (with-current-buffer) expression.

### ISSUE THREAD

**Issue by ssskkkky** [DarwinAwardWinner/with-simulated-input#4]
It seems like that it didn't change the buffer when it's in  a (with-current buffer) expression
try this:

```elisp
(defun test()
  (interactive)
  (let ((file "~/test.org"))
    (setq org-agenda-buffer (if (file-exists-p file)
                                (org-get-agenda-file-buffer file)
                              (error "No such file %s" file)))
    (with-current-buffer org-agenda-buffer
      (with-simulated-input
          "a"
        (test2)))))

(defun test2()
  (and (read-char) (insert "test")))
```

**Comment by DarwinAwardWinner** [comment]
Can you give me an example that doesn't use an org agenda buffer? Unless you think the org agenda buffer is relevant?

**Comment by DarwinAwardWinner** [comment]
Also, can you describe what happens when you run the code, and how it is different from what you expected to happen?

**Comment by ssskkkky** [comment]
(defun test()
(interactive)
(let ((file "~/testt"))
(setq test-buffer (if (file-exists-p file)
                            (get-file-buffer file)
                          (error "No such file %s" file)))
(with-current-buffer test-buffer
  (with-simulated-input
      "a"
  (test2)))))

(defun test2()
  (and (read-char) (insert "test")))

When I call function test in a file buffer named abc or whatever, rather than insert the string "test" to the ~/testt file buffer which was expected , it insert the words in the current buffer.

**Comment by DarwinAwardWinner** [comment]
Ok, thank you. I'll take a look at this when I have the time.

**Comment by DarwinAwardWinner** [comment]
And here's the root cause: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37396#8

**Comment by ssskkkky** [comment]
It works. Thanks.
